Adding tests for OMP_TARGET_OFFLOAD
SOLLVE/sollve_vv pull request #240
Opened 2021-01-06 21:10 UTC by tmh97

Checks behavior when OMP_TARGET_OFFLOAD is set to Disabled, Default, and Mandatory. May need to devise a better way to test mandatory.

2021-01-07 15:52 UTC, tob2 commented
I have not tried the code with GCC mainline (to become GCC 11.0.1), which supports this feature, but I wonder whether the `setenv("OMP_TARGET_OFFLOAD", "DEFAULT", 1);` comes way too late.

Namely, the test program sets it in `main` – but at least for GCC, in libgomp, the environment variables are parsed in as (static) constructor:
```C
static void __attribute__((constructor))
initialize_env (void)
{ …
```

2021-01-07 19:49 UTC, spophale commented
I agree with @tob2 . And that might be the reason why changing it multiple times in the program did not work. We could try to set it with other openmpvv env variables. But we may be able to test only one with that approach.

2021-01-11 17:02 UTC, spophale commented on tests/5.0/program_control/test_omp_target_offload.c
> +   #pragma omp target map(tofrom: on_init_dev)
I think the test will be more meaningful if you added some token computation, e.g. increment variable and copy back.

2021-01-11 17:12 UTC, spophale commented on tests/5.0/program_control/test_omp_target_offload.c
> +   OMPVV_TEST_AND_SET(errors, policy==DEFAULT && isOffloading == 1 && on_init_dev != 0)
The second case is policy = DEFAULT, isoffloading ==0, in that case the computation should be correct and should have executed on host.

2021-01-13 15:09 UTC, spophale requested changes

2021-01-13 15:09 UTC, spophale commented on tests/5.0/program_control/test_omp_target_offload.c
> +// This tet was adopted from OpenMP 5.0 Examples Doc -> target_offload_control.1.c
Typo: test 
Only add this line if most of the code was taken from the examples.

2021-01-14 18:29 UTC, spophale approved these changes

2021-01-15 21:58 UTC, jhdavis8 approved these changes

2021-01-15 22:16 UTC, merged