Add 5.0 tests of parallel master directive
SOLLVE/sollve_vv pull request #276
Opened 2021-02-01 21:23 UTC by jhdavis8

This PR adds tests of the parallel master directive, one on the host and the other in a target region. Currently this test passes Clang and fails GCC due to invalid number of teams returned. I believe this is the same bug identified in PR #269.

2021-02-10 15:11 UTC, spophale commented on tests/5.0/parallel_master/test_parallel_master.c
> +    if (omp_get_thread_num() == 0) {
don't need the check.

2021-02-10 15:24 UTC, spophale commented on tests/5.0/parallel_master/test_parallel_master_device.c
> +#pragma omp target map(tofrom: x, y, z, num_threads)
to: y,z

2021-02-10 15:24 UTC, spophale commented on tests/5.0/parallel_master/test_parallel_master_device.c
> +      if (omp_get_thread_num() == 0) {
don't need this check.

2021-02-10 15:25 UTC, spophale requested changes
see comments.

2021-02-15 18:18 UTC, spophale approved these changes

2021-02-15 18:49 UTC, tmh97 approved these changes

2021-02-18 16:21 UTC, merged