Add 5.0 tests of master taskloop simd directive
SOLLVE/sollve_vv pull request #277
Opened 2021-02-01 21:43 UTC by jhdavis8

This is a test of the master taskloop simd directive on the host and device. It displays the same behavior on the compilers as the other master/taskloop combined directives. Clang issues warnings about not vectorizing the loops.

2021-02-08 20:22 UTC, tmh97 reviewed
good to go

2021-02-10 15:03 UTC, spophale commented on tests/5.0/master_taskloop_simd/test_master_taskloop_simd_device.c
> +#pragma omp target parallel num_threads(OMPVV_NUM_THREADS_DEVICE) shared(x, y, z, num_threads) map(tofrom: x, y, z, num_threads)
y and z don't need to be copied back.

2021-02-10 15:05 UTC, spophale requested changes
Minor change, see comment.

2021-02-15 18:33 UTC, spophale approved these changes

2021-02-15 18:36 UTC, merged