Add 5.0 tests of parallel master taskloop simd directive
SOLLVE/sollve_vv pull request #278
Opened 2021-02-01 21:54 UTC by jhdavis8

These tests check the combined parallel master taskloop simd directive on the device and on the host. The behavior is similar to that of other combined taskloop clauses. GCC fails the host version of the test due to invalid reported number of teams (same bug seen in #269), but in this case, passes the device test. Clang passes both tests but issues a compile time warning indicated the loops were not vectorized.

2021-02-10 14:53 UTC, spophale commented on tests/5.0/parallel_master_taskloop_simd/test_parallel_master_taskloop_simd.c
> +  OMPVV_INFOMSG("This test does not guarantee parallelism of the tested clause.");
Needs a more informative message. What granularity is it referring to (tasking, vectorization or both) ?

2021-02-10 14:54 UTC, spophale commented on tests/5.0/parallel_master_taskloop_simd/test_parallel_master_taskloop_simd_device.c
> +#pragma omp target map(tofrom: x, y, z)
tofrom: x to:y,z

2021-02-10 15:01 UTC, spophale requested changes
See comments.

2021-02-15 18:34 UTC, spophale approved these changes

2021-02-15 18:53 UTC, tmh97 approved these changes

2021-02-18 16:21 UTC, merged