New 5.0 test for target construct with device clause
SOLLVE/sollve_vv pull request #295
Opened 2021-02-22 21:35 UTC by tmh97

Test passes on newest llvm release. GCC seems to be lacking support for device clause, specifically the device-modifier expressions.

2021-03-03 15:44 UTC, spophale commented on tests/5.0/target/test_target_device.c
> +    #pragma omp target device(device_num: 1) map(tofrom: b, which_device)
In all practical situations the assumption that device_num == 1 will work, although device numbers are implementation defined. Ideally the device_num should be set to a value between 0 - omp_get_num_devices() and the value should not be equal to omp_get_device_num() on host.

2021-03-16 21:49 UTC, jhdavis8 approved these changes
Looks good besides minor change

2021-03-16 21:49 UTC, jhdavis8 commented on tests/5.0/target/test_target_device.c
> +    OMPVV_WARNING_IF(which_device != 1, "Target region was executed on device. Due to ancestor device-modifier,"
Should this be ERROR_IF since the errors var is being set if which_device != 1

2021-03-17 13:09 UTC, spophale requested changes
For test_target_device_device_num() - query the number of devices to first check if any are available (before line 55).

2021-03-26 14:38 UTC, tmh97 commented on tests/5.0/target/test_target_device.c
> +
Check that device is actually available, if not issue warning/error

2021-03-27 23:27 UTC, tmh97 commented
@spophale hey just pushed the changes we discussed the last meeting. I used omp_get_device_num() in the target region and it broke things with llvm. I could revert back to using omp_is_initial_device(), but I feel like omp_get_device_num() makes more sense here (line 77)

2021-03-29 21:01 UTC, spophale commented on tests/5.0/target/test_target_device.c
> +    OMPVV_ERROR_IF(omp_get_num_devices() <= 0, "There are no target devices available, cannot properly "
msg --> Since no target devices were found this test will be skipped.

2021-03-29 21:03 UTC, spophale commented on tests/5.0/target/test_target_device.c
> +    OMPVV_ERROR_IF(omp_get_num_devices() <= 0, "There are no target devices available, cannot properly test");
see msg above.

2021-03-29 21:04 UTC, spophale approved these changes
Looks good, just change the error messages.

2021-03-29 22:45 UTC, merged