Add Fortran versions of uses_allocators tests
SOLLVE/sollve_vv pull request #347
Opened 2021-06-07 20:03 UTC by jhdavis8

These do not compile on either of the Summit Fortran compilers

2021-06-09 12:16 UTC, spophale requested changes
The fortran tests themselves look good, the first line in the header still says *.c. Please change it to .F90.

2021-06-15 19:42 UTC, tmh97 approved these changes
Tests look good.

2021-06-18 15:37 UTC, jhdavis8 commented
Fixed the header test names to match the correct file extension.

2021-06-18 15:38 UTC, spophale approved these changes

2021-06-18 15:40 UTC, merged