5.0 Fortran tests of task affinity
SOLLVE/sollve_vv pull request #355
Opened 2021-06-30 03:24 UTC by jhdavis8

These follow the format of the C tests of the feature. They do not compile with any available Summit compiler. I'm not as sure about the way the arrays are allocated and mapped in the device version of this test, so any feedback is appreciated.

2021-08-16 17:38 UTC, spophale commented on tests/5.0/task/test_task_affinity.F90
> +       B(i) = i*2
How about we modify with operation on existing value instead overwriting ?

2021-08-16 17:46 UTC, spophale approved these changes

2021-11-06 18:09 UTC, tob2 commented on tests/5.0/task/test_task_affinity.F90
> +       B(i) += A(i)
Compiles and runs with GCC/gfortran if I change this to `B(i) = B(i) + A(i)`

2021-11-06 18:13 UTC, tob2 requested changes

2021-11-06 18:13 UTC, tob2 commented on tests/5.0/task/test_task_affinity_device.F90
> +       B(i) += A(i)
Likewise, works with GCC/gfortran 12 when changing to
```suggestion
       B(i) = B(i) + A(i)
```

2021-11-08 19:17 UTC, spophale commented
@tob2 , I have approved the change. Is assignment operator a known issue in GCC ?

2021-11-08 21:01 UTC, tob2 commented
> @tob2 , I have approved the change. Is assignment operator a known issue in GCC ?

No, but a known issue **in Fortran** at least until Fortran 2018. _At least I feel reluctant to add this as vendor extension, especially as there is the general trend to go to standard conforming code and it is just syntactical sugar._

However, it is reoccurring topic. See for instance the somewhat recent issue and very recent email discussion at J3:
* Feature request in the J3 issue tracker:  https://github.com/j3-fortran/fortran_proposals/issues/113 
* `+=` discussion in August/September J3 mailing list, at
   https://mailman.j3-fortran.org/pipermail/j3/2021-August/thread.html#13251
   https://mailman.j3-fortran.org/pipermail/j3/2021-September/thread.html#13295

_**J3 is:** “INCITS PL22.3, the US Fortran Programming Language Standards Technical Committee, formerly known as ANSI X3J3 and informally referred to as "J3". J3 is the US National Body for the international Fortran standards committee, ISO/IEC JTC1/SC22/WG5 and is tasked with developing the technical content of Fortran standards.”_

2021-11-08 21:29 UTC, tmh97 approved these changes
looks good

2021-11-11 16:19 UTC, merged