Test target update mapper from discontiguous
SOLLVE/sollve_vv pull request #358
Opened 2021-07-14 14:08 UTC by nolanbaker31

Wrote the code, similar to mapper_to_discontiguous. Let me know if you see any issues!

2021-07-16 17:27 UTC, spophale requested changes
Can you delete the empty file "test_target.c" from the commit.

2021-07-16 17:35 UTC, spophale commented on tests/5.0/target_update/test_target_update_mapper_from_discontiguous.c
> +// to or from clauses may include array sections with stride expressions."
Where is the strided expression used ?
The format should be: 
[ lower-bound : length : stride] or
[ lower-bound : : stride] or
[ : length : stride] or
[ : : stride]

2021-07-16 19:45 UTC, nolanbaker31 reviewed
Unsure exactly how to use stride expressions & their use, feedback is appreciated

2021-07-19 16:24 UTC, spophale commented on tests/5.0/target_update/test_target_update_mapper_from_discontiguous.c
> +#pragma omp declare mapper(newvec_t v) map(v, v.data[0:v.len:2])
So here you are stating that the array should be mapped with stride of 2 starting at lower bound 0. So 0,2,4,6... indices of the array should be mapped by the mapper.

2021-07-19 16:38 UTC, spophale commented on tests/5.0/target_update/test_target_update_mapper_from_discontiguous.c
> +    for (i = 0; i < s.len; i++) {
Here you are accessing all elements of s.data --> the mapper in effect is mapping only even elements. IMO, it should be "i+2".

2021-07-19 16:43 UTC, spophale commented on tests/5.0/target_update/test_target_update_mapper_from_discontiguous.c
> +    OMPVV_TEST_AND_SET(errors, s.data[i] != i);
should test only elements mapped and modified.

2021-08-11 14:28 UTC, tmh97 approved these changes

2021-08-11 14:28 UTC, spophale approved these changes

2021-08-16 17:47 UTC, spophale commented
@nolanbaker31 this is ready to merge or do you want to make any more changes ?

2021-08-16 17:49 UTC, nolanbaker31 commented
@spophale It is ready, but Thomas told me the branch is messed up, so I was about to create a new PR. Do you think it is fine to merge, or should I create a new one?

2021-08-18 14:12 UTC, merged