Add tests/5.0/target/test_target_imperfect_loop.F90
SOLLVE/sollve_vv pull request #463
Opened 2022-02-16 05:18 UTC by seyonglee

With XLF 16.1.1-10, compiled without errors, but runtime error occurs.
With GCC 11.1.0, compilation fails (Error: not enough DO loops for collapsed !$OMP PARALLEL DO at (1)).

2022-02-23 15:49 UTC, spophale requested changes
Re-check data2 error checking.

2022-02-23 18:48 UTC, seyonglee commented on tests/5.0/target/test_target_imperfect_loop.F90
> +          OMPVV_TEST_AND_SET(errors, data2(i,j) .ne. i * j)
@spophale thank you for catching this error; fixed.

2022-03-02 17:23 UTC, spophale approved these changes

2022-03-16 20:13 UTC, nolanbaker31 approved these changes

2022-04-17 22:23 UTC, tmh97 approved these changes
Looks good-to-go. The .c version passes on latest llvm 15 dev build, the .f90 version still failing on gcc/11.2.0 and latest nvhpc available on summit

2022-04-17 22:23 UTC, merged