Add a new test (test/5.0/loop/test_loop_nested_device.F90)
SOLLVE/sollve_vv pull request #646
Opened 2022-12-16 22:06 UTC by seyonglee

- XL 16.1.1-10: C test passed, but tested with one team and one thread
            - Fortran test failed: line 50.10: 1515-019 (S) Syntax is incorrect.
        - NVHPC 22.11:
            - C test failed:
                - NVC++-F-1196-OpenMP - 'omp parallel' in a 'loop' region is not supported yet.  (/gpfs/alpine/csc383/scratch/f6l/sollve/tests/5.0/loop/test_loop_nested_device.c: 46)
            - Fortran test failed:
                - NVFORTRAN-S-1224-LOOP construct may not contain calls to the OpenMP Runtime API - . (/gpfs/alpine/csc383/scratch/f6l/sollve/tests/5.0/loop/test_loop_nested_device.F90: 58)
        - LLVM 15.0.0:
            - C test passed but ran with one thread.
        - GCC 12.2.1: C test passed; Fortran test passed but ran on the host

2023-03-15 18:46 UTC, spophale commented on tests/5.0/loop/test_loop_nested_device.F90
> +    !$omp target teams num_teams(OMPVV_NUM_TEAMS_DEVICE) thread_limit(OMPVV_NUM_THREADS_HOST) map(tofrom: x, y, z, num_teams)
use  OMPVV_NUM_THREADS_DEVICE

2023-03-15 18:53 UTC, spophale requested changes
Use  OMPVV_NUM_THREADS_DEVICE

2023-03-15 20:08 UTC, seyonglee commented on tests/5.0/loop/test_loop_nested_device.F90
> +    !$omp target teams num_teams(OMPVV_NUM_TEAMS_DEVICE) thread_limit(OMPVV_NUM_THREADS_HOST) map(tofrom: x, y, z, num_teams)
Updated; thanks.

2023-03-23 13:32 UTC, spophale approved these changes

2023-04-05 20:03 UTC, jrreap approved these changes

2023-04-12 19:45 UTC, merged