Add new_test/test_atomic_hint.F90
SOLLVE/sollve_vv pull request #684
Opened 2023-02-22 03:17 UTC by seyonglee

- NVHPC 22.11:
            - C test failed: line 25: error: invalid text in pragma
            - Fortran test failed: NVFORTRAN-S-0034-Syntax error at or near identifier hint
        - LLVM 15.0.0: C test passed.
        - LLVM 17.0.0: C test passed.
        - GCC 12.2.1:
            - Both C and Fortran tests passed.
        - XL 16.1.1-10:
            - C test passed, but test ran with one thread, so the results are not conclusive
            - Fortran test failed:  line 37.13: 1515-019 (S) Syntax is incorrect.

2023-03-06 17:29 UTC, spophale commented on tests/5.0/atomic/test_atomic_hint.F90
> +    OMPVV_ERROR_IF(num_threads .LT. 0, "Test ran with invalid number of teams (less than zero)")
threads (not teams)

2023-03-06 17:29 UTC, spophale commented on tests/5.0/atomic/test_atomic_hint.F90
> +    OMPVV_ERROR_IF(num_threads .LT. 0, "Test ran with invalid number of teams (less than zero)")
threads (not teams)

2023-03-06 17:30 UTC, spophale requested changes
Messages need to be corrected.

2023-03-08 01:43 UTC, seyonglee commented on tests/5.0/atomic/test_atomic_hint.F90
> +    OMPVV_ERROR_IF(num_threads .LT. 0, "Test ran with invalid number of teams (less than zero)")
Updated; thanks.

2023-03-08 01:44 UTC, seyonglee commented on tests/5.0/atomic/test_atomic_hint.F90
> +    OMPVV_ERROR_IF(num_threads .LT. 0, "Test ran with invalid number of teams (less than zero)")
Updated; thanks.

2023-03-08 01:44 UTC, seyonglee commented on tests/5.0/atomic/test_atomic_hint.F90
> +    OMPVV_ERROR_IF(num_threads .LT. 0, "Test ran with invalid number of teams (less than zero)")
Updated; thanks.

2023-03-08 01:47 UTC, seyonglee commented
> Messages need to be corrected.

Corrected

2023-03-15 20:45 UTC, spophale approved these changes

2023-04-12 21:25 UTC, mjcarr458 approved these changes

2023-04-13 21:17 UTC, merged