Ordered Doacross - Defined Source
SOLLVE/sollve_vv pull request #701
Opened 2023-04-04 14:56 UTC by nolanbaker31

2023-04-05 14:33 UTC, fel-cab commented on tests/5.2/ordered/test_ordered_doacross_defined_source.c
> +    b[i-1] = a[i-2];
for i=1, a[i-2] is outside the array

2023-08-17 20:47 UTC, andrewkallai commented
Because (source: ) is logically equivalent to (source: omp_cur_iteration) according to the semantics of source on the doacross clause, and according to the restrictions on the doacross clause: "If vector is specified with source as the dependence-type then it must be omp_cur_iteration," is this test necessary? tests/5.2/ordered/test_ordered_doacross.c uses (source: ) for line 44 where source is the dependence-type on the doacross clause. So in that test it is undefined, but equivalent to defining it as (source: omp_cur_iteration).

2023-09-13 15:47 UTC, andrewkallai commented
frontier
clang 18.0.0
42:25: error: 'ordered' directive with 'doacross' clause cannot be closely nested inside ordered region without specified parameter
   42 |     #pragma omp ordered doacross(sink: i-2)
/autofs/nccs-svm1_home1/andrewka/sollve_vv/tests/5.2/ordered/test_ordered_doacross_defined_source.c:44:41: error: expected ')'
   44 |     #pragma omp ordered doacross(source:i-1)
/autofs/nccs-svm1_home1/andrewka/sollve_vv/tests/5.2/ordered/test_ordered_doacross_defined_source.c:44:33: note: to match this '('
   44 |     #pragma omp ordered doacross(source:i-1)
/autofs/nccs-svm1_home1/andrewka/sollve_vv/tests/5.2/ordered/test_ordered_doacross_defined_source.c:44:25: error: 'ordered' directive with 'doacross' clause cannot be closely nested inside ordered region without specified parameter
   44 |     #pragma omp ordered doacross(source:i-1)
3 errors generated.

2024-01-30 21:31 UTC, andrewkallai requested changes
Since omp_cur_iteration is not specified for source, the compiler will error. However, if it is specified, then GCC will accept the clause. Because an undefined source is equivalent to source:omp_cur_iteration, this test is equivalent to the undefined source test. So unless this explicit change is desired to be tested, this test should be dropped.

2024-01-30 21:31 UTC, andrewkallai commented on tests/5.2/ordered/test_ordered_doacross_defined_source.c
> +    #pragma omp ordered doacross(source:i)
```suggestion
    #pragma omp ordered doacross(source:omp_cur_iteration)
```

2024-04-04 17:42 UTC, spophale commented
We already have tests with omp_cur_iteration.

2024-04-04 17:42 UTC, closed without merging